### ISSUE TITLE
Deregistering a writable socket causes an error.

### ISSUE THREAD

**Issue by andrewvc** [andrewvc/learn-ruby-zeromq#1]
Running the latest ffi-rzmq and zmqmachine the following code: 

https://gist.github.com/2b1b44d8ef4fad1a84d8

gives me the error: 

/Users/admin/.rvm/gems/jruby-1.5.1/gems/ffi-rzmq-0.5.0/lib/ffi-rzmq/poll.rb:98:in `deregister': undefined local variable or method`items' for #ZMQ::Poller:0x3e5646a5 (NameError)
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/ffi-rzmq-0.5.0/lib/ffi-rzmq/poll.rb:123:in `deregister_writable'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:288:in`deregister_writable'
    from 003_ZMQMachine/002_a_pub_sub_example.rb:24:in `on_writable'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/sockets/base.rb:181:in`resume_write'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:385:in `poll'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:385:in`each'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:385:in `poll'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:351:in`run_once'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:84:in `run'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:80:in`initialize'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:80:in `new'
    from /Users/admin/.rvm/gems/jruby-1.5.1/gems/zmqmachine-0.3.1/lib/zm/reactor.rb:80:in`run'
    from 003_ZMQMachine/002_a_pub_sub_example.rb:46

**Comment by chuckremes** [comment]
Upgrade to ffi-rzmq 0.5.1 which I released the other day. I forgot to push it to rubygems. I'll do that now.
